apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shadowmesh-production

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: shadowmesh-gateway
    patch: |
      - op: replace
        path: /spec/replicas
        value: 5
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "250m"
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
  - target:
      kind: Ingress
      name: shadowmesh-gateway
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: gateway.shadowmesh.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: gateway.shadowmesh.io
  - target:
      kind: HorizontalPodAutoscaler
      name: shadowmesh-gateway
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 5
      - op: replace
        path: /spec/maxReplicas
        value: 20

commonLabels:
  environment: production
