apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shadowmesh-staging

resources:
  - ../../base

namePrefix: staging-

patches:
  - target:
      kind: Deployment
      name: shadowmesh-gateway
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Ingress
      name: shadowmesh-gateway
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: staging.shadowmesh.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging.shadowmesh.example.com
  - target:
      kind: HorizontalPodAutoscaler
      name: shadowmesh-gateway
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5

commonLabels:
  environment: staging
